version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - deno_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  deno_network:
    driver: bridge

volumes:
  postgres_data:
